### ISSUE TITLE
Setup Django

### ISSUE THREAD

**Issue by nils-prommersberger** [juliushaag/Quafel-PSE-2024#24]

**Comment by AashishKumarYadav** [comment]
**Install the Django**

_Installation instructions are slightly different depending on whether you’re installing a distribution-specific package, downloading the latest official release, or fetching the latest development version._

1.Install [pip](https://pip.pypa.io/). The easiest is to use the [standalone pip installer](https://pip.pypa.io/en/latest/installation/). If your distribution already has pip installed, you might need to update it if it’s outdated. If it’s outdated, you’ll know because installation won’t work.

2.Take a look at [venv](https://docs.python.org/3/tutorial/venv.html). This tool provides isolated Python environments, which are more practical than installing packages systemwide. It also allows installing packages without administrator privileges. The [contributing tutorial](https://docs.djangoproject.com/en/5.0/intro/contributing/) walks through how to create a virtual environment.

3.After you’ve created and activated a virtual environment, enter the command:

`python -m pip install Django`
